### ISSUE TITLE
Changing windows_sdk_path and windows_sdk_version have no effect

### ISSUE THREAD

**Issue by raizam** [timniederhausen/gn-build#4]
Hey, maybe you can help with this: I tried to to change the sdk version to 8.1 but these settings have no effect. both the generated vs project and the ninja files points to latest win10 sdk.

here are my changes in [win/settings.gni](https://github.com/timniederhausen/gn-build/blob/master/toolchain/win/settings.gni)

```
declare_args() {
  # Version of Visual Studio pointed to by the visual_studio_path.
  # Use "2013" for Visual Studio 2013.
  visual_studio_version = "2017"

  # Path to Visual Studio.
  visual_studio_path = ""

  # Windows SDK version to use.
  # Can either be a full Windows 10 SDK number (e.g. 10.0.10240.0),
  # "8.1" for the Windows8.1 SDK or "default" to use the VS default version.
  windows_sdk_version = "8.1"

  # Full path to the Windows SDK, not including a backslash at the end.
  # This value is the default location, override if you have a different
  # installation location.
  windows_sdk_path = "C:\Program Files (x86)\Windows Kits\8.1"

  # Microsoft compiler version number clang-cl will report in _MSC_VER
  # (Defaults to the default version associated with the chosen VS version.)
  clang_msc_ver = 0
}
```

I looked at [SetupToolchain](https://github.com/timniederhausen/gn-build/blob/master/toolchain/win/toolchain.py#L249) function, and it passing only the sdk version from the settings, the path seems ignored. 

Is this the original win/toolchain.py file or you've modified it?
I'm wondering if it needs update from chromium.

**Comment by timniederhausen** [comment]
Hi,

this works for me.
Using the following `args.gn` file I get the correct SDK version:
```
visual_studio_version = "2017"
windows_sdk_version = "8.1"
```
Can you show me your environment variables after running:
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 8.1
```
(replace Community with your edition)

The code handling the Windows SDK version comes originally from Chromium, however they started to just hardcode the SDK version they want/need. In general, most of the toolchain detection has been changed in order to be more flexible.

The SDK version that is shown inside the VS Property pages can be different than the one used to build the code. IDE project generation is handled entirely by gn. exe. If you want to use a different SDK there you have to specify a version on the command-line:
```
gn gen out --ide=vs --winsdk=8.1
```

**Comment by raizam** [comment]
running `gn gen out --ide=vs --winsdk=8.1` worked :)

here is attached the environment variables from my windows 7 machine
[vsvarall.txt](https://github.com/timniederhausen/gn-build/files/2386068/vsvarall.txt)

I'm closing this as it is solved. thanks a lot
